spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/demo_db
    username: albert
    password: albert
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
